name: Build and push docker image

on:
  push:
    branches: [ main ]
      
jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    - name: Check out the repository
      uses: actions/checkout@v2

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

    - name: Login to ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v2

    - name: Docker build 
      run: |
        docker build -t movie_backend .[cite: 2]

    - name: Docker tag and push
      run: |
        docker tag movie_backend:latest 678080238090.dkr.ecr.us-east-2.amazonaws.com/movie_backend:latest[cite: 2]
        docker tag movie_backend:latest 678080238090.dkr.ecr.us-east-2.amazonaws.com/movie_backend:v${GITHUB_RUN_NUMBER}[cite: 2]
        docker push 678080238090.dkr.ecr.us-east-2.amazonaws.com/movie_backend:latest[cite: 2]
        docker push 678080238090.dkr.ecr.us-east-2.amazonaws.com/movie_backend:v${GITHUB_RUN_NUMBER}[cite: 2]
